# Site settings
name: 峰回路转
email: aizi1989010@126.com
author: aihua
url: aihua.science
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/aSynch1889
baseurl: "/aSynch1889.github.io"
description: Actually, less is more!
meta_description: 华子;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: 上善若水.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: aSynch1889
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyang1889
    disqus :
        short_name : luoyang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
